version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: kannada_nginx
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      kannada_net:
    ports:
      - "8081:80"
    restart: always

  php:
    container_name: kannada_php
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./public:/public
    depends_on:
      - mysql
    networks:
      kannada_net:

  mysql:
    container_name: kannada_db
    image: mariadb:10.5.8
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      kannada_net:
    ports:
      - 4306:3306
    env_file:
      - .env

  phpmyadmin:
    container_name: kannada_admin
    depends_on:
      - mysql
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    env_file:
      - .env
    networks:
      kannada_net:

networks:
  kannada_net:
